from gtts import gTTS as gt
import pygame as pyg
import time


class Voice(object):
    def __init__(self):
        print("loading response files...")

    @staticmethod
    def output(file_name, secs):
        pyg.mixer.music.load(file_name)
        pyg.mixer.music.play()
        time.sleep(secs)

    @staticmethod
    def new(text, file_name):
        print("saving new response file...")
        output = gt(text=text, lang='en-uk')
        output.save(file_name)

    @staticmethod
    def aiva():
        print("saving aiva response files...")
        aiva_1 = gt(text='I am ava, your artificially intelligent virtual assistant', lang='en-uk')
        aiva_2 = gt(text='I am an artificially intelligent virtual assistant, or ava for short', lang='en-uk')
        # aiva_3 = gt(text='I am an artificially intelligent virtual assistant of course', lang='en-uk')
        aiva_4 = gt(text='I am ava', lang='en-uk')
        aiva_5 = gt(text='ava', lang='en-uk')
        aiva_6 = gt(text='My name is ava', lang='en-uk')
        # aiva_7 = gt(text='Its spelled AIVA', lang='en-uk')
        # aiva_8 = gt(text='AIVA', lang='en-uk')
        aiva_9 = gt(text='Would you rather call me something different?', lang='en-uk')
        aiva_10 = gt(text='Is there something else you would rather call me?', lang='en-uk')
        aiva_11 = gt(text='Was there something else you would rather call me?', lang='en-uk')
        aiva_12 = gt(text='What would you like to call me?', lang='en-uk')
        aiva_13 = gt(text='What should I go by from here on out?', lang='en-uk')
        aiva_14 = gt(text='What should I go by from now on?', lang='en-uk')
        aiva_1.save("aiva_1.mp3")
        aiva_2.save("aiva_2.mp3")
        # aiva_3.save("aiva_3.mp3")
        aiva_4.save("aiva_4.mp3")
        aiva_5.save("aiva_5.mp3")
        aiva_6.save("aiva_6.mp3")
        # aiva_7.save("aiva_7.mp3")
        # aiva_8.save("aiva_8.mp3")
        aiva_9.save("aiva_9.mp3")
        aiva_10.save("aiva_10.mp3")
        aiva_11.save("aiva_11.mp3")
        aiva_12.save("aiva_12.mp3")
        aiva_13.save("aiva_13.mp3")
        aiva_14.save("aiva_14.mp3")

    @staticmethod
    def attention():
        print("saving attention response files...")
        attention_1 = gt(text='I am listening', lang='en-uk')
        attention_2 = gt(text='How can I help?', lang='en-uk')
        attention_3 = gt(text='Listening sir', lang='en-uk')
        attention_4 = gt(text='I am listening sir', lang='en-uk')
        attention_5 = gt(text='How can I help sir?', lang='en-uk')
        attention_1.save("attention_1.mp3")
        attention_2.save("attention_2.mp3")
        attention_3.save("attention_3.mp3")
        attention_4.save("attention_4.mp3")
        attention_5.save("attention_5.mp3")

    @staticmethod
    def condition():
        print("saving condition response files...")
        condition_1 = gt(text='I am doing wonderfully', lang='en-uk')
        condition_2 = gt(text='Wonderfully sir', lang='en-uk')
        condition_3 = gt(text='Absolutely stellar', lang='en-uk')
        condition_4 = gt(text='Stellar sir', lang='en-uk')
        condition_5 = gt(text='Never better. Thanks for asking', lang='en-uk')
        condition_6 = gt(text='I am doing wonderfully sir', lang='en-uk')
        # condition_7 = gt(text='Absolutely stellar sir', lang='en-uk')
        condition_8 = gt(text='Never better sir. Thanks for asking', lang='en-uk')
        condition_1.save("condition_1.mp3")
        condition_2.save("condition_2.mp3")
        condition_3.save("condition_3.mp3")
        condition_4.save("condition_4.mp3")
        condition_5.save("condition_5.mp3")
        condition_6.save("condition_6.mp3")
        # condition_7.save("condition_7.mp3")
        condition_8.save("condition_8.mp3")

    @staticmethod
    def confirmation():
        print("saving confirmation response files...")
        # confirm_1 = gt(text='Will do', lang='en-uk')
        confirm_2 = gt(text='Got it', lang='en-uk')
        confirm_3 = gt(text='Sure thing', lang='en-uk')
        # confirm_4 = gt(text='Consider it done', lang='en-uk')
        confirm_5 = gt(text='Doing so now', lang='en-uk')
        confirm_6 = gt(text='Here you go', lang='en-uk')
        # confirm_7 = gt(text='On it', lang='en-uk')
        # confirm_8 = gt(text='As you wish', lang='en-uk')
        # confirm_9 = gt(text='Will do sir', lang='en-uk')
        # confirm_10 = gt(text='Got it sir', lang='en-uk')
        # confirm_11 = gt(text='Sure thing sir', lang='en-uk')
        confirm_12 = gt(text='Consider it done sir', lang='en-uk')
        # confirm_13 = gt(text='Doing so now sir', lang='en-uk')
        # confirm_14 = gt(text='Here you go sir', lang='en-uk')
        # confirm_15 = gt(text='On it sir', lang='en-uk')
        # confirm_16 = gt(text='As you wish sir', lang='en-uk')
        confirm_17 = gt(text='Alright', lang='en-uk')
        confirm_18 = gt(text='Alright sir', lang='en-uk')
        confirm_19 = gt(text='Alright then', lang='en-uk')
        # confirm_20 = gt(text='Here is what I found', lang='en-uk')
        confirm_21 = gt(text='Heres what I found', lang='en-uk')
        # confirm_22 = gt(text='Here is what I found sir', lang='en-uk')
        confirm_23 = gt(text='Heres what I found sir', lang='en-uk')
        # confirm_1.save("confirm_1.mp3")
        confirm_2.save("confirm_2.mp3")
        confirm_3.save("confirm_3.mp3")
        # confirm_4.save("confirm_4.mp3")
        confirm_5.save("confirm_5.mp3")
        confirm_6.save("confirm_6.mp3")
        # confirm_7.save("confirm_7.mp3")
        # confirm_8.save("confirm_8.mp3")
        # confirm_9.save("confirm_9.mp3")
        # confirm_10.save("confirm_10.mp3")
        # confirm_11.save("confirm_11.mp3")
        confirm_12.save("confirm_12.mp3")
        # confirm_13.save("confirm_13.mp3")
        # confirm_14.save("confirm_14.mp3")
        # confirm_15.save("confirm_15.mp3")
        # confirm_16.save("confirm_16.mp3")
        confirm_17.save("confirm_17.mp3")
        confirm_18.save("confirm_18.mp3")
        confirm_19.save("confirm_19.mp3")
        # confirm_20.save("confirm_20.mp3")
        confirm_21.save("confirm_21.mp3")
        # confirm_22.save("confirm_22.mp3")
        confirm_23.save("confirm_23.mp3")

    @staticmethod
    def farewell():
        print("saving farewell response files...")
        farewell_1 = gt(text='Terminating. Goodbye', lang='en-uk')
        farewell_2 = gt(text='Terminating systems. Goodbye', lang='en-uk')
        farewell_3 = gt(text='Shutting down. Goodbye', lang='en-uk')
        farewell_4 = gt(text='Shutting down systems. Goodbye', lang='en-uk')
        farewell_5 = gt(text='Shutting down all processes. Goodbye', lang='en-uk')
        # farewell_6 = gt(text='Goodbye', lang='en-uk')
        farewell_7 = gt(text='Terminating. Goodbye sir', lang='en-uk')
        farewell_8 = gt(text='Terminating systems. Goodbye sir', lang='en-uk')
        farewell_9 = gt(text='Shutting down. Goodbye sir', lang='en-uk')
        farewell_10 = gt(text='Shutting down systems. Goodbye sir', lang='en-uk')
        farewell_11 = gt(text='Shutting down all processes. Goodbye sir', lang='en-uk')
        # farewell_12 = gt(text='Goodbye sir', lang='en-uk')
        farewell_1.save("farewell_1.mp3")
        farewell_2.save("farewell_2.mp3")
        farewell_3.save("farewell_3.mp3")
        farewell_4.save("farewell_4.mp3")
        farewell_5.save("farewell_5.mp3")
        # farewell_6.save("farewell_6.mp3")
        farewell_7.save("farewell_7.mp3")
        farewell_8.save("farewell_8.mp3")
        farewell_9.save("farewell_9.mp3")
        farewell_10.save("farewell_10.mp3")
        farewell_11.save("farewell_11.mp3")
        # farewell_12.save("farewell_12.mp3")

    @staticmethod
    def greetings():
        print("saving greeting response files...")
        greeting_1 = gt(text='Hey there', lang='en-uk')
        greeting_2 = gt(text='Hi there', lang='en-uk')
        greeting_3 = gt(text='Hello there', lang='en-uk')
        greeting_4 = gt(text='Hey', lang='en-uk')
        greeting_5 = gt(text='Hi', lang='en-uk')
        greeting_6 = gt(text='Hello', lang='en-uk')
        greeting_1.save("greeting_1.mp3")
        greeting_2.save("greeting_2.mp3")
        greeting_3.save("greeting_3.mp3")
        greeting_4.save("greeting_4.mp3")
        greeting_5.save("greeting_5.mp3")
        greeting_6.save("greeting_6.mp3")

    @staticmethod
    def no():
        print("saving no response files...")
        no_1 = gt(text='I am afraid not', lang='en-uk')
        no_2 = gt(text='No sir', lang='en-uk')
        no_3 = gt(text='Incorrect', lang='en-uk')
        no_4 = gt(text='Not quite', lang='en-uk')
        no_5 = gt(text='I am afraid not sir', lang='en-uk')
        no_6 = gt(text='Incorrect sir', lang='en-uk')
        no_7 = gt(text='Not quite sir', lang='en-uk')
        no_1.save("no_1.mp3")
        no_2.save("no_2.mp3")
        no_3.save("no_3.mp3")
        no_4.save("no_4.mp3")
        no_5.save("no_5.mp3")
        no_6.save("no_6.mp3")
        no_7.save("no_7.mp3")

    @staticmethod
    def recurring():
        print("saving recurring response files...")
        recurring_1 = gt(text='I already told you', lang='en-uk')
        recurring_2 = gt(text='I already told you that', lang='en-uk')
        recurring_3 = gt(text='Last I checked', lang='en-uk')
        recurring_4 = gt(text='I already told you sir', lang='en-uk')
        # recurring_5 = gt(text='I already told you that sir', lang='en-uk')
        recurring_6 = gt(text='Last I checked sir', lang='en-uk')
        recurring_1.save("recurring_1.mp3")
        recurring_2.save("recurring_2.mp3")
        recurring_3.save("recurring_3.mp3")
        recurring_4.save("recurring_4.mp3")
        # recurring_5.save("recurring_5.mp3")
        recurring_6.save("recurring_6.mp3")

    @staticmethod
    def tdgreetings():
        print("saving TD greeting response files...")
        tdgreeting_1 = gt(text='Good morning', lang='en-uk')
        tdgreeting_2 = gt(text='Good afternoon', lang='en-uk')
        tdgreeting_3 = gt(text='Good evening', lang='en-uk')
        tdgreeting_4 = gt(text='Good morning sir', lang='en-uk')
        tdgreeting_5 = gt(text='Good afternoon sir', lang='en-uk')
        tdgreeting_6 = gt(text='Good evening sir', lang='en-uk')
        tdgreeting_1.save("tdgreeting_1.mp3")
        tdgreeting_2.save("tdgreeting_2.mp3")
        tdgreeting_3.save("tdgreeting_3.mp3")
        tdgreeting_4.save("tdgreeting_4.mp3")
        tdgreeting_5.save("tdgreeting_5.mp3")
        tdgreeting_6.save("tdgreeting_6.mp3")

    @staticmethod
    def unsure():
        print("saving unsure response files...")
        # unsure_1 = gt(text='I am afraid I dont know how to answer that', lang='en-uk')
        unsure_2 = gt(text='I dont seem to have an answer to that', lang='en-uk')
        # unsure_3 = gt(text='I dont seem to know how to answer that', lang='en-uk')
        unsure_4 = gt(text='I am afraid I dont have an answer to that', lang='en-uk')
        # unsure_5 = gt(text='I am afraid I dont know how to answer that sir', lang='en-uk')
        unsure_6 = gt(text='I dont seem to have an answer to that sir', lang='en-uk')
        # unsure_7 = gt(text='I dont seem to know how to answer that sir', lang='en-uk')
        unsure_8 = gt(text='I am afraid I dont have an answer to that sir', lang='en-uk')
        # unsure_1.save("unsure_1.mp3")
        unsure_2.save("unsure_2.mp3")
        # unsure_3.save("unsure_3.mp3")
        unsure_4.save("unsure_4.mp3")
        # unsure_5.save("unsure_5.mp3")
        unsure_6.save("unsure_6.mp3")
        # unsure_7.save("unsure_7.mp3")
        unsure_8.save("unsure_8.mp3")

    @staticmethod
    def user():
        print("saving user response files...")
        user_1 = gt(text='Currently you are admin sir', lang='en-uk')
        user_2 = gt(text='Currently you are admin', lang='en-uk')
        # user_3 = gt(text='Youre admin', lang='en-uk')
        user_4 = gt(text='Currently admin sir', lang='en-uk')
        user_5 = gt(text='Is there something else you would rather I call you?', lang='en-uk')
        user_6 = gt(text='Would you rather me call you something different?', lang='en-uk')
        user_7 = gt(text='What would you like me to call you?', lang='en-uk')
        user_8 = gt(text='What should I call you from here on out?', lang='en-uk')
        user_9 = gt(text='What should I call you from now on?', lang='en-uk')
        user_10 = gt(text='How is that spelled?', lang='en-uk')
        user_11 = gt(text='How should I spell that?', lang='en-uk')
        user_12 = gt(text='How do you spell that?', lang='en-uk')
        user_1.save("user_1.mp3")
        user_2.save("user_2.mp3")
        # user_3.save("user_3.mp3")
        user_4.save("user_4.mp3")
        user_5.save("user_5.mp3")
        user_6.save("user_6.mp3")
        user_7.save("user_7.mp3")
        user_8.save("user_8.mp3")
        user_9.save("user_9.mp3")
        user_10.save("user_10.mp3")
        user_11.save("user_11.mp3")
        user_12.save("user_12.mp3")

    @staticmethod
    def welcome():
        print("saving welcome response files...")
        welcome_1 = gt(text='You are welcome', lang='en-uk')
        welcome_2 = gt(text='No problem', lang='en-uk')
        welcome_3 = gt(text='Always a pleasure', lang='en-uk')
        welcome_4 = gt(text='You are welcome sir', lang='en-uk')
        welcome_5 = gt(text='No problem sir', lang='en-uk')
        welcome_6 = gt(text='Always a pleasure sir', lang='en-uk')
        welcome_1.save("welcome_1.mp3")
        welcome_2.save("welcome_2.mp3")
        welcome_3.save("welcome_3.mp3")
        welcome_4.save("welcome_4.mp3")
        welcome_5.save("welcome_5.mp3")
        welcome_6.save("welcome_6.mp3")

    @staticmethod
    def whatup():
        print("saving whatup response files...")
        whatup_1 = gt(text='Nothing much', lang='en-uk')
        whatup_2 = gt(text='Many things. The sky for one', lang='en-uk')
        whatup_3 = gt(text='Not much', lang='en-uk')
        whatup_4 = gt(text='Nothing much sir', lang='en-uk')
        whatup_5 = gt(text='Not much sir', lang='en-uk')
        whatup_1.save("whatup_1.mp3")
        whatup_2.save("whatup_2.mp3")
        whatup_3.save("whatup_3.mp3")
        whatup_4.save("whatup_4.mp3")
        whatup_5.save("whatup_5.mp3")

    @staticmethod
    def yes():
        print("saving yes response files...")
        yes_1 = gt(text='Thats right', lang='en-uk')
        yes_2 = gt(text='Yes sir', lang='en-uk')
        yes_3 = gt(text='Correct', lang='en-uk')
        yes_4 = gt(text='Thats right sir', lang='en-uk')
        yes_5 = gt(text='Correct sir', lang='en-uk')
        yes_1.save("yes_1.mp3")
        yes_2.save("yes_2.mp3")
        yes_3.save("yes_3.mp3")
        yes_4.save("yes_4.mp3")
        yes_5.save("yes_5.mp3")

    @staticmethod
    def german():
        print("saving german response files...")
        german_1 = gt(text='es ist', lang='de')
        german_2 = gt(text='gut', lang='de')
        german_3 = gt(text='guten morgen', lang='de')
        german_4 = gt(text='und', lang='de')
        german_5 = gt(text='willkommen', lang='de')
        german_6 = gt(text='wollen', lang='de')
        german_7 = gt(text='sie', lang='de')
        german_8 = gt(text='was', lang='de')
        german_9 = gt(text='wasser', lang='de')
        german_10 = gt(text='essen', lang='de')
        german_11 = gt(text='trinken', lang='de')
        german_12 = gt(text='wollen sie?', lang='de')
        german_13 = gt(text='was wollen sie?', lang='de')
        german_1.save("german_1.mp3")
        german_2.save("german_2.mp3")
        german_3.save("german_3.mp3")
        german_4.save("german_4.mp3")
        german_5.save("german_5.mp3")
        german_6.save("german_6.mp3")
        german_7.save("german_7.mp3")
        german_8.save("german_8.mp3")
        german_9.save("german_9.mp3")
        german_10.save("german_10.mp3")
        german_11.save("german_11.mp3")
        german_12.save("german_12.mp3")
        german_13.save("german_13.mp3")


if __name__ == "__main__":
    voice = Voice()
    '''
    voice.aiva()
    voice.attention()
    voice.condition()
    voice.confirmation()
    voice.farewell()
    voice.greetings()
    voice.no()
    voice.recurring()
    voice.tdgreetings()
    voice.unsure()
    voice.user()
    voice.welcome()
    voice.whatup()
    voice.yes()
    '''
    voice.german()
